In [1]:
import pandas as pd
from bulletin.utils.normalize import normalize_text
from bulletin.utils.static import Municipios

---------------------------------------------------------------

root: C:\sesa\covid19datascience\bulletin
parent: C:\sesa\covid19datascience
default_input: C:\sesa\covid19datascience\input
default_output: C:\sesa\covid19datascience\output

---------------------------------------------------------------

In [4]:
mun = Municipios().groupby(['uf','estado']).count().reset_index()
est = mun[['uf','estado']].copy()
est['estado'] = est['estado'].apply(normalize_text)

In [5]:
rt = pd.read_excel('rt.xlsx')
rt.columns = ['uf','rt']

rt = pd.merge(est,rt,on='uf',how='left')
rt

    uf               estado    rt
0   AC                 ACRE  0.93
1   AL              ALAGOAS  1.00
2   AM             AMAZONAS  0.95
3   AP                AMAPA  0.95
4   BA                BAHIA  0.98
5   CE                CEARA  0.95
6   DF     DISTRITO FEDERAL  0.98
7   ES       ESPIRITO SANTO  0.95
8   GO                GOIAS   NaN
9   IG    IGNORADO/EXTERIOR   NaN
10  MA             MARANHAO  0.99
11  MG         MINAS GERAIS   NaN
12  MS   MATO GROSSO DO SUL   NaN
13  MT          MATO GROSSO  1.00
14  PA                 PARA  0.89
15  PB              PARAIBA   NaN
16  PE           PERNAMBUCO   NaN
17  PI                PIAUI  0.97
18  PR               PARANA  0.91
19  RJ       RIO DE JANEIRO  0.94
20  RN  RIO GRANDE DO NORTE  0.90
21  RO             RONDONIA  0.97
22  RR              RORAIMA  1.00
23  RS    RIO GRANDE DO SUL   NaN
24  SC       SANTA CATARINA  0.98
25  SE              SERGIPE   NaN
26  SP            SAO PAULO   NaN
27  TO            TOCANTINS  1.01

In [6]:
inferno = pd.read_excel('inferno.xlsx')
inferno.columns = [ x.lower() for x in inferno.columns ]
inferno['estado'] = inferno['estado'].apply(normalize_text)

inferno = pd.merge(inferno, rt, on='estado',how='left')

In [10]:
inferno.sort_values('vacinas aplicadas').to_excel('rt_vacina.xlsx')